### PR TITLE
bruh typos

### PR DESCRIPTION
**Pull request by faluhub**

### CODE REVIEW

**Review by VIGHNESH-Y — CHANGES_REQUESTED** [review]
That is just a read me file

**Comment by faluhub** [comment]
so?

**Comment by VIGHNESH-Y** [comment]
No one is gonna check for grammar mistakes

**Comment by faluhub** [comment]
well apparently I did

**Comment by faluhub** [comment]
> No one is gonna check for grammar mistakes

Noone*

**Pull request closed without merging**
